# Generated by Django 4.2.2 on 2024-03-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='malayalam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_no', models.CharField(max_length=255)),
                ('malayalam_title', models.CharField(max_length=255)),
                ('english_title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('year_of_dc', models.IntegerField()),
                ('year_pub', models.IntegerField()),
                ('other_pub', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='northeast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('accession_number', models.IntegerField()),
                ('class_number', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('collection', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='sindhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('accession_number', models.IntegerField()),
                ('author_first_name', models.CharField(max_length=255)),
                ('author_last_name', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
            ],
        ),
    ]
