# Generated by Django 4.2.2 on 2024-03-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sindhi',
            name='accession_number',
            field=models.CharField(max_length=255),
        ),
    ]
