# Generated by Django 4.2.2 on 2024-03-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0003_alter_malayalam_year_of_dc_alter_malayalam_year_pub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nunber', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
