# Generated by Django 4.2.2 on 2024-03-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nunber',
            new_name='number',
        ),
    ]
