# Generated by Django 4.2.2 on 2024-03-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0006_language_literary_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='literary_work',
            name='others',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
