# Generated by Django 4.2.2 on 2024-03-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0007_literary_work_others'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literary_work',
            old_name='publish_year',
            new_name='language1',
        ),
    ]
